import 'dart:convert';
import 'dart:io';

import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;

import '../console/artisan_command.dart';
import '../console/artisan_context.dart';
import '../console/command_boot.dart';
import '../helpers/config_editor.dart';
import '../helpers/file_helper.dart';
import '../stubs/stub_loader.dart';
import 'make_fast_cli_command.dart';

/// `install` — scaffold the canonical native Flutter consumer
/// (`bin/dispatcher.dart` + `lib/app/_plugins.g.dart` + initial
/// `lib/app/commands/_index.g.dart`) into the current project AND
/// auto-chain `make:fast-cli` so `bin/fsa` lands in the same invocation.
///
/// Idempotent: skips files that already exist; pass `--force` to
/// overwrite.
///
/// Magic-installed consumers reach the same canonical state by routing
/// `magic:install` through this command in-process. Vanilla Flutter
/// consumers use `dart run fluttersdk_artisan install` directly.
final class InstallCommand extends ArtisanCommand {
  @override
  String get signature => 'install '
      '{--force : Overwrite files even when they already exist}';

  @override
  String get description =>
      'Scaffold the canonical Flutter consumer (bin/dispatcher.dart + barrels) '
      'and install bin/fsa fast-CLI.';

  @override
  CommandBoot get boot => CommandBoot.none;

  @override
  Future<int> handle(ArtisanContext ctx) async {
    final force = ctx.input.option('force') as bool? ?? false;
    final root = FileHelper.findProjectRoot();
    return scaffoldInto(root: root, force: force, ctx: ctx);
  }

  /// Testable entry point. Writes the 3 canonical files into [root], injects
  /// the `fluttersdk_artisan` pubspec dep (path-dep when package_config
  /// resolves it locally, `any` otherwise), then chains to
  /// `MakeFastCliCommand.scaffoldInto` so `bin/fsa` + `.gitignore` + AOT
  /// bundle land in the same invocation.
  ///
  /// Idempotent across all phases:
  /// - Each of the 3 file writes skips when the target already exists unless
  ///   [force] is true.
  /// - Pubspec dep injection is a no-op when `fluttersdk_artisan` is already
  ///   listed under `dependencies:` (via `ConfigEditor`).
  /// - The auto-chained `MakeFastCliCommand.scaffoldInto` is itself
  ///   idempotent (per its docblock).
  ///
  /// Returns 0 on success, 1 on missing pubspec name, and propagates any
  /// non-zero exit from the auto-chained `MakeFastCliCommand`.
  @visibleForTesting
  static Future<int> scaffoldInto({
    required String root,
    required bool force,
    required ArtisanContext ctx,
  }) async {
    // 1. Read consumer name from pubspec.yaml. Without it the stub cannot
    //    substitute the `{{ name }}` placeholder for the two `package:` imports
    //    that wire the codegen barrels into the dispatcher.
    final consumerName = _readConsumerName(root);
    if (consumerName == null) {
      ctx.output.error(
        'Could not read `name:` from $root/pubspec.yaml. '
        'Run `install` from a Dart/Flutter project root.',
      );
      return 1;
    }

    var wrote = 0;
    var skipped = 0;

    // 2. bin/dispatcher.dart — canonical consumer wrapper rendered from the
    //    `dispatcher.dart.stub` template with the consumer package name.
    final dispatcherPath = p.join(root, 'bin', 'dispatcher.dart');
    if (_shouldWrite(dispatcherPath, force)) {
      final raw = StubLoader.load('dispatcher.dart');
      final rendered = StubLoader.replace(raw, {'name': consumerName});
      FileHelper.writeFile(dispatcherPath, rendered);
      ctx.output.success('Created: $dispatcherPath');
      wrote++;
    } else {
      ctx.output.info('Skipped (exists): $dispatcherPath');
      skipped++;
    }

    // 3. lib/app/_plugins.g.dart — initial empty barrel for the plugin
    //    provider list. Regenerated by `plugin:install` / `plugins:refresh`.
    final pluginsGPath = p.join(root, 'lib', 'app', '_plugins.g.dart');
    if (_shouldWrite(pluginsGPath, force)) {
      final raw = StubLoader.load('consumer_plugins_g.dart');
      FileHelper.writeFile(pluginsGPath, raw);
      ctx.output.success('Created: $pluginsGPath');
      wrote++;
    } else {
      ctx.output.info('Skipped (exists): $pluginsGPath');
      skipped++;
    }

    // 4. lib/app/commands/_index.g.dart — initial empty consumer command
    //    list. Regenerated by `commands:refresh` / `make:command`.
    final indexPath = p.join(root, 'lib', 'app', 'commands', '_index.g.dart');
    if (_shouldWrite(indexPath, force)) {
      final raw = StubLoader.load('consumer_commands_index_initial.dart');
      FileHelper.writeFile(indexPath, raw);
      ctx.output.success('Created: $indexPath');
      wrote++;
    } else {
      ctx.output.info('Skipped (exists): $indexPath');
      skipped++;
    }

    // 5. pubspec dep injection. The codegen barrels at phases 3 + 4 import
    //    from `package:fluttersdk_artisan/artisan.dart`; without a direct dep
    //    in the consumer pubspec the analyzer flags every barrel with
    //    `depend_on_referenced_packages`. Two routing modes:
    //    a. monorepo / path-dep workflow: read .dart_tool/package_config.json,
    //       find the artisan rootUri, inject as a path dep so the consumer
    //       pubspec resolves the same artisan checkout that already powers
    //       the in-flight `dart run fluttersdk_artisan` invocation.
    //    b. pub.dev workflow (no package_config or artisan resolved from a
    //       pub-cache absolute URI): inject `fluttersdk_artisan: any`.
    //    ConfigEditor is idempotent in both branches.
    final pubspecPath = p.join(root, 'pubspec.yaml');
    final relativeArtisan = _resolveArtisanRelativePath(root);
    if (relativeArtisan != null) {
      ConfigEditor.addPathDependencyToPubspec(
        pubspecPath: pubspecPath,
        name: 'fluttersdk_artisan',
        path: relativeArtisan,
      );
    } else {
      ConfigEditor.addDependencyToPubspec(
        pubspecPath: pubspecPath,
        name: 'fluttersdk_artisan',
        version: 'any',
      );
    }

    ctx.output.info(
      'Install scaffold complete ($wrote written, $skipped skipped). '
      'Chaining make:fast-cli for bin/fsa setup.',
    );

    // 6. Auto-chain make:fast-cli IN-PROCESS so a single `install` invocation
    //    yields the full canonical state (dispatcher + barrels + pubspec dep
    //    + bin/fsa + AOT bundle). Process-spawning here would lose stdout
    //    sharing + cost ~3s startup; the static entry preserves both.
    final fastCliExitCode = await MakeFastCliCommand.scaffoldInto(
      root: root,
      force: force,
      ctx: ctx,
    );
    if (fastCliExitCode != 0) {
      ctx.output.error(
        'install: auto-chained make:fast-cli failed (exit $fastCliExitCode). '
        'Re-run `make:fast-cli --force` after fixing the underlying issue.',
      );
      return fastCliExitCode;
    }

    return 0;
  }

  /// Returns true when [path] does not exist OR [force] is set.
  static bool _shouldWrite(String path, bool force) {
    if (force) return true;
    return !File(path).existsSync();
  }

  /// Extracts the package name from `<root>/pubspec.yaml`. Returns null
  /// when the file is missing or has no `name:` line.
  ///
  /// Extraction to a shared helper deferred per the extract-when-third-caller
  /// rule.
  static String? _readConsumerName(String root) {
    final pubspec = File(p.join(root, 'pubspec.yaml'));
    if (!pubspec.existsSync()) return null;
    final match = RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(
      pubspec.readAsStringSync(),
    );
    return match?.group(1);
  }

  /// Resolves the on-disk path to `fluttersdk_artisan` relative to the
  /// consumer's pubspec.yaml location. Reads
  /// `<consumerRoot>/.dart_tool/package_config.json`, locates the
  /// `fluttersdk_artisan` entry, and rebases its `rootUri` (relative to
  /// `.dart_tool/`) onto [consumerRoot]. Returns null when the file is
  /// missing, malformed, or when artisan resolves to a pub-cache location
  /// (in which case the caller falls back to a version-constraint dep).
  ///
  /// See `_readConsumerName` extraction rationale above.
  static String? _resolveArtisanRelativePath(String consumerRoot) {
    final configFile = File(
      p.join(consumerRoot, '.dart_tool', 'package_config.json'),
    );
    if (!configFile.existsSync()) return null;

    final Object? decoded;
    try {
      decoded = jsonDecode(configFile.readAsStringSync());
    } catch (_) {
      return null;
    }
    if (decoded is! Map<String, dynamic>) return null;
    final packages = decoded['packages'];
    if (packages is! List) return null;

    for (final entry in packages) {
      if (entry is! Map) continue;
      if (entry['name'] != 'fluttersdk_artisan') continue;
      final rootUri = entry['rootUri'];
      if (rootUri is! String) return null;
      // Pub-cache resolutions start with `file://` absolute URIs; only
      // path-dep workflows yield a relative rootUri suitable for a path: dep.
      if (rootUri.startsWith('file://')) return null;
      if (p.isAbsolute(rootUri)) return null;
      // rootUri is relative to .dart_tool/ inside the consumer; rebase to
      // be relative to the consumer's pubspec.yaml location.
      final absolute = p.normalize(
        p.join(consumerRoot, '.dart_tool', rootUri),
      );
      final relativeToConsumer = p.relative(absolute, from: consumerRoot);
      return relativeToConsumer;
    }
    return null;
  }
}
