import 'dart:io';

/// Line-based `.env` file editor for CLI install commands.
///
/// Provides safe, idempotent read/write operations for `.env` files without
/// relying on any third-party `.env` parser. Each method operates line-by-line
/// to preserve user comments, blank lines, and key ordering.
///
/// Quoting rule: if a value contains spaces, `#`, `"`, `'`, or `$`, the value
/// is wrapped in double quotes and any inner double quotes are backslash-escaped.
/// All other values are emitted bare.
///
/// ## Usage
///
/// ```dart
/// // Write (or update) a key.
/// EnvEditor.setKey('/app/.env', 'APP_ENV', 'production');
///
/// // Write with an explanatory comment above the line.
/// EnvEditor.setKey('/app/.env', 'APP_KEY', 'base64:abc...', comment: 'Generated by key:generate');
///
/// // Read the current value.
/// final env = EnvEditor.getKey('/app/.env', 'APP_ENV'); // 'production'
///
/// // Check presence.
/// if (!EnvEditor.hasKey('/app/.env', 'APP_DEBUG')) {
///   EnvEditor.setKey('/app/.env', 'APP_DEBUG', 'false');
/// }
///
/// // Remove a key (and its leading comment).
/// EnvEditor.removeKey('/app/.env', 'LEGACY_KEY');
/// ```
class EnvEditor {
  EnvEditor._();

  // ---------------------------------------------------------------------------
  // Public static API
  // ---------------------------------------------------------------------------

  /// Set or update [key] to [value] in the `.env` file at [envPath].
  ///
  /// Behaviour:
  /// - Creates the file if it does not exist.
  /// - Updates the value in-place when [key] already exists (preserving its
  ///   position and all surrounding lines).
  /// - Appends a new `KEY=VALUE` line when [key] is absent.
  /// - When [comment] is supplied, a `# <comment>` line is prepended
  ///   immediately above the `KEY=VALUE` line (for new keys) or replaces the
  ///   existing comment above the key line (for updates).
  ///
  /// Values are quoted if they contain spaces, `#`, `"`, `'`, or `$`.
  ///
  /// @param envPath  Absolute or relative path to the `.env` file.
  /// @param key      Environment variable name (upper-case by convention).
  /// @param value    Raw value; quoting is applied automatically.
  /// @param comment  Optional single-line comment text (without `#` prefix).
  static void setKey(
    String envPath,
    String key,
    String value, {
    String? comment,
  }) {
    // 1. Load existing lines (empty list when file is absent).
    final file = File(envPath);
    final lines = file.existsSync() ? file.readAsLinesSync() : <String>[];

    // 2. Locate the existing key line index (if any).
    final keyPrefix = '$key=';
    final keyIndex = _findKeyIndex(lines, keyPrefix);

    final encoded = _encode(value);
    final keyLine = '$key=$encoded';

    if (keyIndex == -1) {
      // 3a. Key not present: append (with optional comment).
      if (comment != null) {
        lines.add('# $comment');
      }
      lines.add(keyLine);
    } else {
      // 3b. Key present: replace the value in-place. Also handle comment.
      lines[keyIndex] = keyLine;

      if (comment != null) {
        // Replace or insert the comment immediately above the key line.
        if (keyIndex > 0 && lines[keyIndex - 1].startsWith('#')) {
          lines[keyIndex - 1] = '# $comment';
        } else {
          lines.insert(keyIndex, '# $comment');
        }
      }
    }

    // 4. Write back, ensuring a trailing newline.
    _writeLines(file, lines);
  }

  /// Read the current raw value for [key] from the `.env` file at [envPath].
  ///
  /// Returns `null` when the file does not exist or [key] is not present.
  /// Quoted values are unquoted before being returned (outer double quotes
  /// stripped, inner `\"` sequences unescaped).
  ///
  /// @param envPath  Path to the `.env` file.
  /// @param key      Environment variable name.
  /// @return         Raw (unquoted) string value, or `null` if absent.
  static String? getKey(String envPath, String key) {
    final file = File(envPath);
    if (!file.existsSync()) return null;

    final keyPrefix = '$key=';
    for (final line in file.readAsLinesSync()) {
      if (line.startsWith(keyPrefix)) {
        final raw = line.substring(keyPrefix.length);
        return _decode(raw);
      }
    }
    return null;
  }

  /// Delete the [key] line (and the comment immediately above it, if any)
  /// from the `.env` file at [envPath].
  ///
  /// Idempotent: no-op when the key is absent or the file does not exist.
  ///
  /// @param envPath  Path to the `.env` file.
  /// @param key      Environment variable name to remove.
  static void removeKey(String envPath, String key) {
    final file = File(envPath);
    if (!file.existsSync()) return;

    final lines = file.readAsLinesSync();
    final keyPrefix = '$key=';
    final keyIndex = _findKeyIndex(lines, keyPrefix);

    if (keyIndex == -1) return;

    // Remove the comment line immediately above the key line, if present.
    if (keyIndex > 0 && lines[keyIndex - 1].startsWith('#')) {
      lines.removeAt(keyIndex - 1);
      // After removal the key line shifted up by one.
      lines.removeAt(keyIndex - 1);
    } else {
      lines.removeAt(keyIndex);
    }

    _writeLines(file, lines);
  }

  /// Return `true` when [key] exists in the `.env` file at [envPath].
  ///
  /// Returns `false` when the file does not exist or [key] is not present.
  ///
  /// @param envPath  Path to the `.env` file.
  /// @param key      Environment variable name.
  /// @return         `true` if the key is present.
  static bool hasKey(String envPath, String key) {
    return getKey(envPath, key) != null || _fileContainsKey(envPath, '$key=');
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /// Return the index of the first line that starts with [keyPrefix], or -1.
  static int _findKeyIndex(List<String> lines, String keyPrefix) {
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].startsWith(keyPrefix)) return i;
    }
    return -1;
  }

  /// Encode [value] according to the quoting rule.
  ///
  /// Values containing spaces, `#`, `"`, `'`, or `$` are wrapped in
  /// double quotes with inner double quotes backslash-escaped.
  static String _encode(String value) {
    final needsQuotes = value.contains(' ') ||
        value.contains('#') ||
        value.contains('"') ||
        value.contains("'") ||
        value.contains(r'$');

    if (!needsQuotes) return value;

    final escaped = value.replaceAll('"', r'\"');
    return '"$escaped"';
  }

  /// Decode a raw value string from a `.env` line.
  ///
  /// Strips outer double quotes and unescapes inner `\"` sequences.
  static String _decode(String raw) {
    if (raw.startsWith('"') && raw.endsWith('"') && raw.length >= 2) {
      final inner = raw.substring(1, raw.length - 1);
      return inner.replaceAll(r'\"', '"');
    }
    return raw;
  }

  /// Write [lines] back to [file] with a trailing newline.
  static void _writeLines(File file, List<String> lines) {
    if (!file.parent.existsSync()) {
      file.parent.createSync(recursive: true);
    }
    file.writeAsStringSync('${lines.join('\n')}\n');
  }

  /// Return true if [file] exists and any line starts with [keyPrefix].
  ///
  /// Used as the fallback branch in [hasKey] for keys whose value is empty
  /// string (which [getKey] would still return as non-null, so this branch
  /// is reached only via the outer `||` when getKey returns null for a
  /// key with an empty value edge case). In practice this guards the case
  /// where the encoded value is an empty string.
  static bool _fileContainsKey(String envPath, String keyPrefix) {
    final file = File(envPath);
    if (!file.existsSync()) return false;
    return file.readAsLinesSync().any((l) => l.startsWith(keyPrefix));
  }
}
