name: example_magic
description: "E2E test: Magic framework + fluttersdk_artisan via plugin:install."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  magic:
    path: ../../magic

  magic_logger:
    path: ../example/packages/magic_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  fluttersdk_artisan:
    path: ../
  fluttersdk_dusk:
    path: ../../fluttersdk_dusk
  fluttersdk_telescope:
    path: ../../fluttersdk_telescope
  fluttersdk_wind:
    path: ../../wind

flutter:
  uses-material-design: true
