name: example_magic
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  magic:
    path: ../../magic

  my_plugin:
    path: ./packages/my_plugin

dependency_overrides:
  fluttersdk_artisan:
    path: ../
  fluttersdk_dusk:
    path: ../../fluttersdk_dusk
  fluttersdk_telescope:
    path: ../../fluttersdk_telescope
  fluttersdk_wind:
    path: ../../wind

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
workspace:
  - packages/my_plugin
